version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "kohbis"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "kohbis"
